<?php

namespace Database\Seeders;

use App\Models\Classroom;
use App\Models\Exam;
use App\Models\Module;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ExamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $exams = [
            [
                "exam_id" => 1,
                "module_id" => "LFA36104",
                "semester_id" => 6,
                "classroom_id" => "1",
                "teacher_ids" => "26,97,170",
                "group_ids" => "2,9,12",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 2,
                "module_id" => "LFB36104",
                "semester_id" => 6,
                "classroom_id" => "2",
                "teacher_ids" => "35,79,194",
                "group_ids" => "4,6,12",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 3,
                "module_id" => "LFF36104",
                "semester_id" => 6,
                "classroom_id" => "4",
                "teacher_ids" => "39,54,119",
                "group_ids" => "4,9,12",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 4,
                "module_id" => "LFF12104",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "38,53,101",
                "group_ids" => "1,10,11",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 5,
                "module_id" => "LFR36104",
                "semester_id" => 6,
                "classroom_id" => "9",
                "teacher_ids" => "21,98,105",
                "group_ids" => "3,10,12",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 6,
                "module_id" => "LFA12104",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "38,99,110",
                "group_ids" => "4,6,11",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 7,
                "module_id" => "LFA12104",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "50,82,186",
                "group_ids" => "1,8,12",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 8,
                "module_id" => "LFF12104",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "37,57,103",
                "group_ids" => "1,6,11",
                "day" => "2023-07-11",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 9,
                "module_id" => "LFA36204",
                "semester_id" => 6,
                "classroom_id" => "1",
                "teacher_ids" => "13,69,125",
                "group_ids" => "2,6,11",
                "day" => "2023-07-11",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 10,
                "module_id" => "LFB36204",
                "semester_id" => 6,
                "classroom_id" => "2",
                "teacher_ids" => "5,93,149",
                "group_ids" => "1,9,12",
                "day" => "2023-07-11",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 11,
                "module_id" => "LFF36204",
                "semester_id" => 6,
                "classroom_id" => "4",
                "teacher_ids" => "35,89,190",
                "group_ids" => "3,8,11",
                "day" => "2023-07-11",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 12,
                "module_id" => "LFR36204",
                "semester_id" => 6,
                "classroom_id" => "9",
                "teacher_ids" => "49,57,199",
                "group_ids" => "3,7,12",
                "day" => "2023-07-11",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 13,
                "module_id" => "LFF12204",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "12,96,183",
                "group_ids" => "1,10,11",
                "day" => "2023-07-11",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 14,
                "module_id" => "LFF12204",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "11,82,133",
                "group_ids" => "1,10,11",
                "day" => "2023-07-11",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 15,
                "module_id" => "LFA12204",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "24,88,181",
                "group_ids" => "3,8,11",
                "day" => "2023-07-11",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 16,
                "module_id" => "LFF24104",
                "semester_id" => 4,
                "classroom_id" => "A",
                "teacher_ids" => "30,81,196",
                "group_ids" => "1,6,12",
                "day" => "2023-07-11",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 17,
                "module_id" => "LFF24104",
                "semester_id" => 4,
                "classroom_id" => "B",
                "teacher_ids" => "28,91,125",
                "group_ids" => "2,5,11",
                "day" => "2023-07-11",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 18,
                "module_id" => "LFA24204",
                "semester_id" => 4,
                "classroom_id" => "C",
                "teacher_ids" => "12,69,166",
                "group_ids" => "1,8,12",
                "day" => "2023-07-11",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 19,
                "module_id" => "LFA24304",
                "semester_id" => 4,
                "classroom_id" => "5",
                "teacher_ids" => "14,100,167",
                "group_ids" => "1,6,12",
                "day" => "2023-07-11",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 20,
                "module_id" => "LFF24204",
                "semester_id" => 4,
                "classroom_id" => "A",
                "teacher_ids" => "46,53,170",
                "group_ids" => "4,6,11",
                "day" => "2023-07-11",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 21,
                "module_id" => "LFF24204",
                "semester_id" => 4,
                "classroom_id" => "B",
                "teacher_ids" => "50,58,127",
                "group_ids" => "3,7,11",
                "day" => "2023-07-11",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 22,
                "module_id" => "LFA36304",
                "semester_id" => 6,
                "classroom_id" => "1",
                "teacher_ids" => "37,98,175",
                "group_ids" => "2,10,12",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 23,
                "module_id" => "LFB36304",
                "semester_id" => 6,
                "classroom_id" => "2",
                "teacher_ids" => "6,63,128",
                "group_ids" => "4,6,11",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 24,
                "module_id" => "LFR36304",
                "semester_id" => 6,
                "classroom_id" => "3",
                "teacher_ids" => "14,65,116",
                "group_ids" => "1,6,12",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 25,
                "module_id" => "LFF36304",
                "semester_id" => 6,
                "classroom_id" => "4",
                "teacher_ids" => "32,54,165",
                "group_ids" => "3,5,11",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 26,
                "module_id" => "LFF12504",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "50,86,191",
                "group_ids" => "3,7,11",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 27,
                "module_id" => "LFA12304",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "39,66,128",
                "group_ids" => "1,8,11",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 28,
                "module_id" => "LFA12304",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "38,68,125",
                "group_ids" => "3,9,12",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 29,
                "module_id" => "LFF12504",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "4,60,107",
                "group_ids" => "4,5,12",
                "day" => "2023-07-12",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 30,
                "module_id" => "LFA36404",
                "semester_id" => 6,
                "classroom_id" => "1",
                "teacher_ids" => "38,53,102",
                "group_ids" => "3,7,12",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 31,
                "module_id" => "LFB36404",
                "semester_id" => 6,
                "classroom_id" => "2",
                "teacher_ids" => "12,79,155",
                "group_ids" => "2,10,11",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 32,
                "module_id" => "LFR36404",
                "semester_id" => 6,
                "classroom_id" => "3",
                "teacher_ids" => "31,86,104",
                "group_ids" => "2,7,11",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 33,
                "module_id" => "LFF36404",
                "semester_id" => 6,
                "classroom_id" => "4",
                "teacher_ids" => "8,100,188",
                "group_ids" => "2,8,11",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 34,
                "module_id" => "LFF12604",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "10,54,121",
                "group_ids" => "4,9,11",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 35,
                "module_id" => "LFA12404",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "8,73,149",
                "group_ids" => "4,9,12",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 36,
                "module_id" => "LFA12404",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "17,53,175",
                "group_ids" => "1,8,12",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 37,
                "module_id" => "LFF12604",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "31,96,113",
                "group_ids" => "3,6,12",
                "day" => "2023-07-12",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 38,
                "module_id" => "LFE24104",
                "semester_id" => 4,
                "classroom_id" => "3",
                "teacher_ids" => "4,73,167",
                "group_ids" => "2,5,11",
                "day" => "2023-07-12",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 39,
                "module_id" => "LFE24104",
                "semester_id" => 4,
                "classroom_id" => "5",
                "teacher_ids" => "46,58,162",
                "group_ids" => "1,8,12",
                "day" => "2023-07-12",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 40,
                "module_id" => "LFE24104",
                "semester_id" => 4,
                "classroom_id" => "9",
                "teacher_ids" => "37,69,121",
                "group_ids" => "3,7,11",
                "day" => "2023-07-12",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 41,
                "module_id" => "LFA24104",
                "semester_id" => 4,
                "classroom_id" => "A",
                "teacher_ids" => "30,70,176",
                "group_ids" => "2,9,11",
                "day" => "2023-07-12",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 42,
                "module_id" => "LFF24404",
                "semester_id" => 4,
                "classroom_id" => "B",
                "teacher_ids" => "22,58,159",
                "group_ids" => "4,10,11",
                "day" => "2023-07-12",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 43,
                "module_id" => "LFE24104",
                "semester_id" => 4,
                "classroom_id" => "C",
                "teacher_ids" => "45,72,167",
                "group_ids" => "3,9,12",
                "day" => "2023-07-12",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 44,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "1",
                "teacher_ids" => "30,82,105",
                "group_ids" => "3,5,12",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 45,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "3",
                "teacher_ids" => "24,67,162",
                "group_ids" => "2,10,12",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 46,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "5",
                "teacher_ids" => "10,72,150",
                "group_ids" => "1,10,11",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 47,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "9",
                "teacher_ids" => "16,54,190",
                "group_ids" => "2,6,12",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 48,
                "module_id" => "LFF24604",
                "semester_id" => 4,
                "classroom_id" => "A",
                "teacher_ids" => "37,86,141",
                "group_ids" => "3,7,12",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 49,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "B",
                "teacher_ids" => "25,67,116",
                "group_ids" => "1,6,12",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 50,
                "module_id" => "LFA24504",
                "semester_id" => 4,
                "classroom_id" => "C",
                "teacher_ids" => "26,78,110",
                "group_ids" => "2,6,11",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 51,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "PAV1",
                "teacher_ids" => "35,53,130",
                "group_ids" => "3,6,11",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 52,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "PAV2",
                "teacher_ids" => "23,57,200",
                "group_ids" => "3,7,12",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 53,
                "module_id" => "LFE24304",
                "semester_id" => 4,
                "classroom_id" => "PAV3",
                "teacher_ids" => "33,76,162",
                "group_ids" => "2,8,12",
                "day" => "2023-07-12",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 54,
                "module_id" => "LFF12404",
                "semester_id" => 2,
                "classroom_id" => "1",
                "teacher_ids" => "11,63,180",
                "group_ids" => "3,6,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 55,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "10",
                "teacher_ids" => "44,69,121",
                "group_ids" => "1,9,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 56,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "11",
                "teacher_ids" => "8,52,181",
                "group_ids" => "4,6,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 57,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "12",
                "teacher_ids" => "28,52,197",
                "group_ids" => "4,9,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 58,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "13",
                "teacher_ids" => "1,80,128",
                "group_ids" => "1,7,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 59,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "14",
                "teacher_ids" => "5,59,127",
                "group_ids" => "2,7,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 60,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "15",
                "teacher_ids" => "46,84,147",
                "group_ids" => "4,7,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 61,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "16",
                "teacher_ids" => "39,57,172",
                "group_ids" => "2,7,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 62,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "17",
                "teacher_ids" => "30,97,182",
                "group_ids" => "3,5,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 63,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "18",
                "teacher_ids" => "30,57,162",
                "group_ids" => "1,8,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 64,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "19",
                "teacher_ids" => "22,63,196",
                "group_ids" => "2,8,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 65,
                "module_id" => "LFA12504",
                "semester_id" => 2,
                "classroom_id" => "2",
                "teacher_ids" => "31,60,130",
                "group_ids" => "4,6,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 66,
                "module_id" => "LFF12404",
                "semester_id" => 2,
                "classroom_id" => "3",
                "teacher_ids" => "45,78,180",
                "group_ids" => "2,8,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 67,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "4",
                "teacher_ids" => "26,77,130",
                "group_ids" => "1,8,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 68,
                "module_id" => "LFF12404",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "14,57,154",
                "group_ids" => "1,9,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 69,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "6",
                "teacher_ids" => "17,55,148",
                "group_ids" => "1,7,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 70,
                "module_id" => "LFA12504",
                "semester_id" => 2,
                "classroom_id" => "9",
                "teacher_ids" => "28,89,198",
                "group_ids" => "1,6,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 71,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "5,52,190",
                "group_ids" => "1,5,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 72,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "44,78,172",
                "group_ids" => "3,6,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 73,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "7,77,107",
                "group_ids" => "2,9,11",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 74,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "PAV1",
                "teacher_ids" => "29,100,154",
                "group_ids" => "3,10,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 75,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "PAV2",
                "teacher_ids" => "38,62,115",
                "group_ids" => "2,9,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 76,
                "module_id" => "LFE12104",
                "semester_id" => 2,
                "classroom_id" => "PAV3",
                "teacher_ids" => "41,73,182",
                "group_ids" => "1,6,12",
                "day" => "2023-07-13",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 77,
                "module_id" => "LFA12604",
                "semester_id" => 2,
                "classroom_id" => "1",
                "teacher_ids" => "18,99,179",
                "group_ids" => "1,8,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 78,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "10",
                "teacher_ids" => "33,81,105",
                "group_ids" => "4,8,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 79,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "11",
                "teacher_ids" => "32,75,179",
                "group_ids" => "1,8,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 80,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "12",
                "teacher_ids" => "26,70,196",
                "group_ids" => "2,7,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 81,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "13",
                "teacher_ids" => "22,87,163",
                "group_ids" => "4,8,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 82,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "14",
                "teacher_ids" => "12,57,103",
                "group_ids" => "2,10,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 83,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "15",
                "teacher_ids" => "30,92,146",
                "group_ids" => "2,7,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 84,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "16",
                "teacher_ids" => "30,57,128",
                "group_ids" => "1,9,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 85,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "17",
                "teacher_ids" => "17,69,116",
                "group_ids" => "2,5,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 86,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "18",
                "teacher_ids" => "50,74,117",
                "group_ids" => "4,6,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 87,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "19",
                "teacher_ids" => "12,73,144",
                "group_ids" => "1,7,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 88,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "2",
                "teacher_ids" => "12,98,102",
                "group_ids" => "2,9,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 89,
                "module_id" => "LFF12304",
                "semester_id" => 2,
                "classroom_id" => "3",
                "teacher_ids" => "23,99,102",
                "group_ids" => "1,8,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 90,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "4",
                "teacher_ids" => "37,70,121",
                "group_ids" => "4,5,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 91,
                "module_id" => "LFA12604",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "8,62,104",
                "group_ids" => "4,8,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 92,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "6",
                "teacher_ids" => "38,92,102",
                "group_ids" => "4,6,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 93,
                "module_id" => "LFF12304",
                "semester_id" => 2,
                "classroom_id" => "9",
                "teacher_ids" => "48,53,130",
                "group_ids" => "3,9,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 94,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "3,54,115",
                "group_ids" => "2,9,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 95,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "5,57,129",
                "group_ids" => "4,5,11",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 96,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "18,89,159",
                "group_ids" => "2,7,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 97,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "PAV1",
                "teacher_ids" => "3,99,159",
                "group_ids" => "1,9,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 98,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "PAV2",
                "teacher_ids" => "1,72,117",
                "group_ids" => "4,6,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 99,
                "module_id" => "LFE12304",
                "semester_id" => 2,
                "classroom_id" => "PAV3",
                "teacher_ids" => "25,63,167",
                "group_ids" => "2,8,12",
                "day" => "2023-07-13",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 100,
                "module_id" => "LFA24404",
                "semester_id" => 4,
                "classroom_id" => "1",
                "teacher_ids" => "40,74,165",
                "group_ids" => "1,6,12",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 101,
                "module_id" => "LFF24504",
                "semester_id" => 4,
                "classroom_id" => "2",
                "teacher_ids" => "34,75,140",
                "group_ids" => "3,6,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 102,
                "module_id" => "LFF24504",
                "semester_id" => 4,
                "classroom_id" => "3",
                "teacher_ids" => "21,64,115",
                "group_ids" => "3,7,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 103,
                "module_id" => "LFE24204",
                "semester_id" => 4,
                "classroom_id" => "4",
                "teacher_ids" => "9,69,135",
                "group_ids" => "2,8,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 104,
                "module_id" => "LFA24404",
                "semester_id" => 4,
                "classroom_id" => "5",
                "teacher_ids" => "23,63,178",
                "group_ids" => "2,10,12",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 105,
                "module_id" => "LFF24504",
                "semester_id" => 4,
                "classroom_id" => "9",
                "teacher_ids" => "11,71,136",
                "group_ids" => "4,5,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 106,
                "module_id" => "LFE24204",
                "semester_id" => 4,
                "classroom_id" => "A",
                "teacher_ids" => "48,68,132",
                "group_ids" => "3,5,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 107,
                "module_id" => "LFE24204",
                "semester_id" => 4,
                "classroom_id" => "B",
                "teacher_ids" => "1,100,184",
                "group_ids" => "1,9,12",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 108,
                "module_id" => "LFE24204",
                "semester_id" => 4,
                "classroom_id" => "C",
                "teacher_ids" => "31,78,117",
                "group_ids" => "2,10,12",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 109,
                "module_id" => "LFE24204",
                "semester_id" => 4,
                "classroom_id" => "PAV1",
                "teacher_ids" => "39,88,119",
                "group_ids" => "1,6,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 110,
                "module_id" => "LFE24204",
                "semester_id" => 4,
                "classroom_id" => "PAV2",
                "teacher_ids" => "20,69,134",
                "group_ids" => "4,5,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 111,
                "module_id" => "LFE24204",
                "semester_id" => 4,
                "classroom_id" => "PAV3",
                "teacher_ids" => "7,81,157",
                "group_ids" => "2,6,11",
                "day" => "2023-07-13",
                "start_time" => "14:00",
                "end_time" => "15:30",
            ],
            [
                "exam_id" => 112,
                "module_id" => "LFF24304",
                "semester_id" => 4,
                "classroom_id" => "1",
                "teacher_ids" => "31,57,136",
                "group_ids" => "2,5,12",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 113,
                "module_id" => "LFF24304",
                "semester_id" => 4,
                "classroom_id" => "2",
                "teacher_ids" => "10,88,137",
                "group_ids" => "2,6,12",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 114,
                "module_id" => "LFA24604",
                "semester_id" => 4,
                "classroom_id" => "3",
                "teacher_ids" => "17,98,184",
                "group_ids" => "1,10,11",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 115,
                "module_id" => "LFF24304",
                "semester_id" => 4,
                "classroom_id" => "4",
                "teacher_ids" => "26,77,198",
                "group_ids" => "1,5,11",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 116,
                "module_id" => "LFF24304",
                "semester_id" => 4,
                "classroom_id" => "5",
                "teacher_ids" => "42,72,162",
                "group_ids" => "2,10,11",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 117,
                "module_id" => "LFF24304",
                "semester_id" => 4,
                "classroom_id" => "9",
                "teacher_ids" => "22,94,190",
                "group_ids" => "4,5,12",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 118,
                "module_id" => "LFE24404",
                "semester_id" => 4,
                "classroom_id" => "A",
                "teacher_ids" => "11,75,139",
                "group_ids" => "2,8,12",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 119,
                "module_id" => "LFE24404",
                "semester_id" => 4,
                "classroom_id" => "B",
                "teacher_ids" => "14,61,175",
                "group_ids" => "2,6,11",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 120,
                "module_id" => "LFE24404",
                "semester_id" => 4,
                "classroom_id" => "C",
                "teacher_ids" => "41,70,128",
                "group_ids" => "1,7,12",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 121,
                "module_id" => "LFE24404",
                "semester_id" => 4,
                "classroom_id" => "PAV1",
                "teacher_ids" => "44,91,194",
                "group_ids" => "1,9,12",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 122,
                "module_id" => "LFE24404",
                "semester_id" => 4,
                "classroom_id" => "PAV2",
                "teacher_ids" => "16,60,146",
                "group_ids" => "4,5,12",
                "day" => "2023-07-13",
                "start_time" => "15:45",
                "end_time" => "17:15",
            ],
            [
                "exam_id" => 123,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "1",
                "teacher_ids" => "2,89,200",
                "group_ids" => "2,5,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 124,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "10",
                "teacher_ids" => "47,83,196",
                "group_ids" => "2,8,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 125,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "11",
                "teacher_ids" => "24,61,188",
                "group_ids" => "2,6,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 126,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "12",
                "teacher_ids" => "32,95,161",
                "group_ids" => "1,5,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 127,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "13",
                "teacher_ids" => "22,84,118",
                "group_ids" => "1,6,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 128,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "14",
                "teacher_ids" => "27,80,164",
                "group_ids" => "2,10,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 129,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "15",
                "teacher_ids" => "24,58,158",
                "group_ids" => "4,10,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 130,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "16",
                "teacher_ids" => "36,99,168",
                "group_ids" => "1,9,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 131,
                "module_id" => "LFE36604",
                "semester_id" => 6,
                "classroom_id" => "17",
                "teacher_ids" => "45,52,104",
                "group_ids" => "2,6,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 132,
                "module_id" => "LFE36604",
                "semester_id" => 6,
                "classroom_id" => "18",
                "teacher_ids" => "19,65,106",
                "group_ids" => "2,9,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 133,
                "module_id" => "LFE36604",
                "semester_id" => 6,
                "classroom_id" => "19",
                "teacher_ids" => "43,83,182",
                "group_ids" => "1,9,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 134,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "2",
                "teacher_ids" => "33,90,136",
                "group_ids" => "1,9,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 135,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "3",
                "teacher_ids" => "32,53,179",
                "group_ids" => "4,5,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 136,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "4",
                "teacher_ids" => "43,51,190",
                "group_ids" => "1,10,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 137,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "4,94,123",
                "group_ids" => "3,5,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 138,
                "module_id" => "LFN36604",
                "semester_id" => 6,
                "classroom_id" => "6",
                "teacher_ids" => "14,61,167",
                "group_ids" => "4,5,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 139,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "9",
                "teacher_ids" => "19,99,114",
                "group_ids" => "4,6,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 140,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "50,88,200",
                "group_ids" => "4,5,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 141,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "45,99,168",
                "group_ids" => "4,9,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 142,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "32,58,125",
                "group_ids" => "3,8,12",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 143,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "PAV1",
                "teacher_ids" => "33,98,163",
                "group_ids" => "1,5,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 144,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "PAV2",
                "teacher_ids" => "24,71,113",
                "group_ids" => "2,5,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 145,
                "module_id" => "LFE12504",
                "semester_id" => 2,
                "classroom_id" => "PAV3",
                "teacher_ids" => "16,73,171",
                "group_ids" => "1,9,11",
                "day" => "2023-07-14",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 146,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "1",
                "teacher_ids" => "37,73,187",
                "group_ids" => "1,8,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 147,
                "module_id" => "LFN36404",
                "semester_id" => 6,
                "classroom_id" => "10",
                "teacher_ids" => "30,85,171",
                "group_ids" => "1,8,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 148,
                "module_id" => "LFN36404",
                "semester_id" => 6,
                "classroom_id" => "11",
                "teacher_ids" => "44,68,163",
                "group_ids" => "4,6,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 149,
                "module_id" => "LFN36404",
                "semester_id" => 6,
                "classroom_id" => "12",
                "teacher_ids" => "42,82,148",
                "group_ids" => "3,8,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 150,
                "module_id" => "LFN36404",
                "semester_id" => 6,
                "classroom_id" => "13",
                "teacher_ids" => "13,55,116",
                "group_ids" => "4,5,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 151,
                "module_id" => "LFN36404",
                "semester_id" => 6,
                "classroom_id" => "14",
                "teacher_ids" => "21,83,104",
                "group_ids" => "2,9,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 152,
                "module_id" => "LFE36104",
                "semester_id" => 6,
                "classroom_id" => "15",
                "teacher_ids" => "48,90,165",
                "group_ids" => "3,9,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 153,
                "module_id" => "LFE36104",
                "semester_id" => 6,
                "classroom_id" => "16",
                "teacher_ids" => "39,88,200",
                "group_ids" => "3,7,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 154,
                "module_id" => "LFE36104",
                "semester_id" => 6,
                "classroom_id" => "17",
                "teacher_ids" => "29,60,142",
                "group_ids" => "1,10,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 155,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "2",
                "teacher_ids" => "37,92,199",
                "group_ids" => "1,7,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 156,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "3",
                "teacher_ids" => "44,97,142",
                "group_ids" => "1,10,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 157,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "4",
                "teacher_ids" => "39,67,102",
                "group_ids" => "1,5,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 158,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "15,88,147",
                "group_ids" => "4,6,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 159,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "6",
                "teacher_ids" => "15,62,190",
                "group_ids" => "4,6,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 160,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "9",
                "teacher_ids" => "12,59,149",
                "group_ids" => "4,9,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 161,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "27,83,169",
                "group_ids" => "2,5,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 162,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "6,58,136",
                "group_ids" => "1,8,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 163,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "30,80,122",
                "group_ids" => "2,6,11",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 164,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "PAV1",
                "teacher_ids" => "42,60,139",
                "group_ids" => "2,5,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 165,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "PAV2",
                "teacher_ids" => "31,52,134",
                "group_ids" => "3,6,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 166,
                "module_id" => "LFE12404",
                "semester_id" => 2,
                "classroom_id" => "PAV3",
                "teacher_ids" => "21,94,172",
                "group_ids" => "4,9,12",
                "day" => "2023-07-14",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 167,
                "module_id" => "LFE24504",
                "semester_id" => 4,
                "classroom_id" => "3",
                "teacher_ids" => "14,71,130",
                "group_ids" => "1,7,12",
                "day" => "2023-07-14",
                "start_time" => "15:00",
                "end_time" => "16:30",
            ],
            [
                "exam_id" => 168,
                "module_id" => "LFE24504",
                "semester_id" => 4,
                "classroom_id" => "A",
                "teacher_ids" => "11,61,186",
                "group_ids" => "1,10,11",
                "day" => "2023-07-14",
                "start_time" => "15:00",
                "end_time" => "16:30",
            ],
            [
                "exam_id" => 169,
                "module_id" => "LFE24504",
                "semester_id" => 4,
                "classroom_id" => "B",
                "teacher_ids" => "25,90,198",
                "group_ids" => "2,5,12",
                "day" => "2023-07-14",
                "start_time" => "15:00",
                "end_time" => "16:30",
            ],
            [
                "exam_id" => 170,
                "module_id" => "LFE24504",
                "semester_id" => 4,
                "classroom_id" => "C",
                "teacher_ids" => "20,80,101",
                "group_ids" => "3,8,12",
                "day" => "2023-07-14",
                "start_time" => "15:00",
                "end_time" => "16:30",
            ],
            [
                "exam_id" => 171,
                "module_id" => "LFE24604",
                "semester_id" => 4,
                "classroom_id" => "C",
                "teacher_ids" => "26,72,131",
                "group_ids" => "2,8,12",
                "day" => "2023-07-14",
                "start_time" => "16:45",
                "end_time" => "18:15",
            ],
            [
                "exam_id" => 172,
                "module_id" => "LFE36404",
                "semester_id" => 6,
                "classroom_id" => "1",
                "teacher_ids" => "23,89,136",
                "group_ids" => "4,8,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 173,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "10",
                "teacher_ids" => "23,72,118",
                "group_ids" => "3,5,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 174,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "11",
                "teacher_ids" => "48,71,104",
                "group_ids" => "1,10,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 175,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "12",
                "teacher_ids" => "46,91,172",
                "group_ids" => "4,6,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 176,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "13",
                "teacher_ids" => "3,52,141",
                "group_ids" => "2,8,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 177,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "14",
                "teacher_ids" => "49,57,150",
                "group_ids" => "2,9,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 178,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "15",
                "teacher_ids" => "29,84,105",
                "group_ids" => "3,7,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 179,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "16",
                "teacher_ids" => "24,72,142",
                "group_ids" => "4,9,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 180,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "17",
                "teacher_ids" => "47,78,137",
                "group_ids" => "3,5,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 181,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "18",
                "teacher_ids" => "8,57,110",
                "group_ids" => "4,10,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 182,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "19",
                "teacher_ids" => "19,82,130",
                "group_ids" => "2,10,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 183,
                "module_id" => "LFE36404",
                "semester_id" => 6,
                "classroom_id" => "2",
                "teacher_ids" => "26,57,126",
                "group_ids" => "3,7,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 184,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "3",
                "teacher_ids" => "14,62,187",
                "group_ids" => "1,6,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 185,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "4",
                "teacher_ids" => "19,76,169",
                "group_ids" => "1,10,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 186,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "15,53,146",
                "group_ids" => "2,6,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 187,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "6",
                "teacher_ids" => "20,79,145",
                "group_ids" => "1,6,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 188,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "9",
                "teacher_ids" => "41,94,121",
                "group_ids" => "1,7,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 189,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "42,54,177",
                "group_ids" => "2,9,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 190,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "31,95,146",
                "group_ids" => "4,6,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 191,
                "module_id" => "LFE12204",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "12,67,170",
                "group_ids" => "2,7,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 192,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "PAV1",
                "teacher_ids" => "1,77,138",
                "group_ids" => "3,7,12",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 193,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "PAV2",
                "teacher_ids" => "43,86,125",
                "group_ids" => "3,6,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 194,
                "module_id" => "LFN36104",
                "semester_id" => 6,
                "classroom_id" => "PAV3",
                "teacher_ids" => "23,100,104",
                "group_ids" => "1,9,11",
                "day" => "2023-07-15",
                "start_time" => "09:00",
                "end_time" => "10:30",
            ],
            [
                "exam_id" => 195,
                "module_id" => "LFE36504",
                "semester_id" => 6,
                "classroom_id" => "1",
                "teacher_ids" => "7,90,157",
                "group_ids" => "3,7,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 196,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "10",
                "teacher_ids" => "41,69,141",
                "group_ids" => "1,5,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 197,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "11",
                "teacher_ids" => "29,79,168",
                "group_ids" => "4,9,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 198,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "12",
                "teacher_ids" => "33,72,154",
                "group_ids" => "2,5,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 199,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "13",
                "teacher_ids" => "49,89,170",
                "group_ids" => "3,6,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 200,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "14",
                "teacher_ids" => "5,54,140",
                "group_ids" => "1,6,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 201,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "15",
                "teacher_ids" => "5,88,166",
                "group_ids" => "4,5,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 202,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "16",
                "teacher_ids" => "17,63,161",
                "group_ids" => "3,10,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 203,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "17",
                "teacher_ids" => "42,97,179",
                "group_ids" => "4,8,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 204,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "18",
                "teacher_ids" => "16,95,163",
                "group_ids" => "3,9,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 205,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "19",
                "teacher_ids" => "2,59,187",
                "group_ids" => "4,10,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 206,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "2",
                "teacher_ids" => "35,95,180",
                "group_ids" => "2,10,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 207,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "3",
                "teacher_ids" => "2,61,133",
                "group_ids" => "4,8,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 208,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "4",
                "teacher_ids" => "23,67,114",
                "group_ids" => "4,7,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 209,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "17,67,117",
                "group_ids" => "2,7,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 210,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "6",
                "teacher_ids" => "10,73,185",
                "group_ids" => "1,7,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 211,
                "module_id" => "LFN36504",
                "semester_id" => 6,
                "classroom_id" => "9",
                "teacher_ids" => "10,51,145",
                "group_ids" => "3,6,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 212,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "9,69,143",
                "group_ids" => "2,10,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 213,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "45,81,133",
                "group_ids" => "4,6,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 214,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "47,74,154",
                "group_ids" => "4,8,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 215,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "PAV1",
                "teacher_ids" => "11,90,188",
                "group_ids" => "4,5,12",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 216,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "PAV2",
                "teacher_ids" => "9,63,127",
                "group_ids" => "1,8,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 217,
                "module_id" => "LFE12604",
                "semester_id" => 2,
                "classroom_id" => "PAV3",
                "teacher_ids" => "37,52,197",
                "group_ids" => "1,6,11",
                "day" => "2023-07-15",
                "start_time" => "10:45",
                "end_time" => "12:15",
            ],
            [
                "exam_id" => 218,
                "module_id" => "LFA12704",
                "semester_id" => 2,
                "classroom_id" => "1",
                "teacher_ids" => "36,67,134",
                "group_ids" => "3,10,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 219,
                "module_id" => "LFA12704",
                "semester_id" => 2,
                "classroom_id" => "10",
                "teacher_ids" => "49,92,102",
                "group_ids" => "3,6,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 220,
                "module_id" => "LFA12704",
                "semester_id" => 2,
                "classroom_id" => "11",
                "teacher_ids" => "6,71,122",
                "group_ids" => "1,8,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 221,
                "module_id" => "LFF12704",
                "semester_id" => 2,
                "classroom_id" => "12",
                "teacher_ids" => "30,70,191",
                "group_ids" => "1,7,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 222,
                "module_id" => "LFF12704",
                "semester_id" => 2,
                "classroom_id" => "13",
                "teacher_ids" => "1,59,103",
                "group_ids" => "3,9,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 223,
                "module_id" => "LFF12704",
                "semester_id" => 2,
                "classroom_id" => "14",
                "teacher_ids" => "42,67,123",
                "group_ids" => "3,9,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 224,
                "module_id" => "LFA12704",
                "semester_id" => 2,
                "classroom_id" => "2",
                "teacher_ids" => "35,57,141",
                "group_ids" => "4,5,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 225,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "3",
                "teacher_ids" => "34,63,196",
                "group_ids" => "3,6,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 226,
                "module_id" => "LFA12704",
                "semester_id" => 2,
                "classroom_id" => "4",
                "teacher_ids" => "48,55,158",
                "group_ids" => "4,8,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 227,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "5",
                "teacher_ids" => "14,62,178",
                "group_ids" => "3,5,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 228,
                "module_id" => "LFA12704",
                "semester_id" => 2,
                "classroom_id" => "6",
                "teacher_ids" => "31,62,147",
                "group_ids" => "1,8,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 229,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "9",
                "teacher_ids" => "38,75,122",
                "group_ids" => "4,10,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 230,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "A",
                "teacher_ids" => "39,87,101",
                "group_ids" => "1,9,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 231,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "B",
                "teacher_ids" => "15,78,181",
                "group_ids" => "1,8,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 232,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "C",
                "teacher_ids" => "41,76,140",
                "group_ids" => "2,9,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 233,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "PAV1",
                "teacher_ids" => "14,97,156",
                "group_ids" => "1,9,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 234,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "PAV2",
                "teacher_ids" => "42,61,119",
                "group_ids" => "4,5,12",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
            [
                "exam_id" => 235,
                "module_id" => "LFE12704",
                "semester_id" => 2,
                "classroom_id" => "PAV3",
                "teacher_ids" => "14,67,161",
                "group_ids" => "4,10,11",
                "day" => "2023-07-15",
                "start_time" => "14:00",
                "end_time" => "15:00",
            ],
        ];

        foreach ($exams as $row) {
            Exam::factory()->create([
                "exam_id" => $row['exam_id'],
                "module_id" => Module::where('module_code', '=', $row['module_id'])->first()->module_id,
                "semester_id" => $row['semester_id'],
                "classroom_id" => Classroom::where('classroom_code', 'like', '%' . $row['classroom_id'])->first(),
                "teacher_ids" => $row['teacher_ids'],
                "group_ids" => $row['group_ids'],
                "day" => $row['day'],
                "start_time" => $row['start_time'],
                "end_time" => $row['end_time'],
            ]);
        }
    }
}
