<?php

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Seeder;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $classes = [
            'FLANGLG' => 1,
            'FLANGLT' => 2,
            'FLARALG' => 3,
            'FLARALT' => 4,
            'FLFRADD' => 5,
            'FLFRALG' => 6,
            'FLFRALT' => 7,
            'LFARABE' => 8,
            'LFENGLI' => 9,
            'LFFRANC' => 10,
            'LPMARTM' => 11,
            'LPMARTS' => 12,
            'PLMARAV' => 13,
            'PLMARDG' => 14,
            'PLMTHAC' => 15,
            'PLMTHSC' => 16
        ];

        $modules = [
            [
                "module_id" => 1,
                "module_code" => "FLEL1110",
                "name" => "Grammar 1",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 2,
                "module_code" => "FLEL1120",
                "name" => "Paragraph Writing",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 3,
                "module_code" => "FLEL1130",
                "name" => "Reading Comprehension &  Precis 1",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 4,
                "module_code" => "FLEL1140",
                "name" => "Spoken English",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 5,
                "module_code" => "FLEL1150",
                "name" => "Guided Reading 1",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 6,
                "module_code" => "FLEL1160",
                "name" => "Foreign Languages",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 7,
                "module_code" => "FLEL1170",
                "name" => "Soft Skills (Méthodologie du Travail Universitaire)",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 8,
                "module_code" => "FLEL1210",
                "name" => "Grammar 2",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 9,
                "module_code" => "FLEL1220",
                "name" => "Composition",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 10,
                "module_code" => "FLEL1230",
                "name" => "Reading Comprehension & Precis 2",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 11,
                "module_code" => "FLEL1240",
                "name" => "Oral Communication",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 12,
                "module_code" => "FLEL1250",
                "name" => "Guided Reading 2",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 13,
                "module_code" => "FLEL1260",
                "name" => "Foreign Languages (Français )",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 14,
                "module_code" => "FLEL1270",
                "name" => "Digital Skills (Culture D",
                "class_ids" => "FLANGLT,FLANGLG",
            ],
            [
                "module_id" => 15,
                "module_code" => "FLAL1110",
                "name" => "النحو 1 ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 16,
                "module_code" => "FLAL1120",
                "name" => "مدخل إلى علوم اللغة ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 17,
                "module_code" => "FLAL1130",
                "name" => "الصرف  ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 18,
                "module_code" => "FLAL1140",
                "name" => "نصوص نثرية ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 19,
                "module_code" => "FLAL1150",
                "name" => "تاريخ المغرب ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 20,
                "module_code" => "FLAL1160",
                "name" => "اللغات الأجنبية الفرنسية و الإنجليزية ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 21,
                "module_code" => "FLAL1170",
                "name" => "منهجية العمل الجامعي ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 22,
                "module_code" => "FLAL1210",
                "name" => "البلاغة  ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 23,
                "module_code" => "FLAL1220",
                "name" => "مدخل إلى الأدب وفنونه ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 24,
                "module_code" => "FLAL1230",
                "name" => "صواتة ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 25,
                "module_code" => "FLAL1240",
                "name" => "نصوص شعرية ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 26,
                "module_code" => "FLAL1250",
                "name" => "مدخل إلى التراث الثقافي ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 27,
                "module_code" => "FLAL1260",
                "name" => "اللغات الأجنبية الفرنسية و الانجليزية ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 28,
                "module_code" => "FLAL1270",
                "name" => "الثقافة الرقمية ",
                "class_ids" => "FLARALT,FLARALG",
            ],
            [
                "module_id" => 29,
                "module_code" => "FLFL1110",
                "name" => "ELEMENTS DE GRAMMAIRE I",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 30,
                "module_code" => "FLFL1120",
                "name" => "PHONETIQUE",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 31,
                "module_code" => "FLFL1130",
                "name" => "TECHNIQUES D\'EXPRESSION ET DE COMMUNICATION ECRITES (TECE)",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 32,
                "module_code" => "FLFL1140",
                "name" => "LECTURE METHODIQUE DES TEXTES LITTERAIRES  1",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 33,
                "module_code" => "FLFL1150",
                "name" => "HISTOIRE DES IDEES (17e SIECLE)",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 34,
                "module_code" => "FLFL1160",
                "name" => "METHODOLOGIE DE TRAVAIL UNIVERSITAIRE",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 35,
                "module_code" => "FLFL1170",
                "name" => "LANGUES ETRANGERES ( Anglais)",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 36,
                "module_code" => "FLFL1210",
                "name" => "GRAMMAIRE II",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 37,
                "module_code" => "FLFL1220",
                "name" => "LEXICOGRAPHIE",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 38,
                "module_code" => "FLFL1230",
                "name" => "TECHNIQUES D\'EXPRESSION ET DE COMMUNICATION ORALES",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 39,
                "module_code" => "FLFL1240",
                "name" => "LECTURE METHODIQUE DES TEXTES LITT?RAIRES 2",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 40,
                "module_code" => "FLFL1250",
                "name" => "HISTOIRE DES IDEES (18ème siècle)",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 41,
                "module_code" => "FLFL1260",
                "name" => "CULTURE DIGITALE",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 42,
                "module_code" => "FLFL1270",
                "name" => "LANGUES ETRANGERES ( Anglais)",
                "class_ids" => "FLFRALT,FLFRADD,FLFRALG",
            ],
            [
                "module_id" => 43,
                "module_code" => "LFA11104",
                "name" => "Grammaire1",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 44,
                "module_code" => "LFA11204",
                "name" => "Introduction à la linguistique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 45,
                "module_code" => "LFA11304",
                "name" => "Introduction à la littérature arabe",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 46,
                "module_code" => "LFA11404",
                "name" => "Réthorique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 47,
                "module_code" => "LFA11504",
                "name" => "Prosodie",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 48,
                "module_code" => "LFA11604",
                "name" => "Civilisation islamique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 49,
                "module_code" => "LFA11704",
                "name" => "Langues",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 50,
                "module_code" => "LFA12104",
                "name" => "Grammaire2",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 51,
                "module_code" => "LFA12204",
                "name" => "Philologie",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 52,
                "module_code" => "LFA12304",
                "name" => "Poésie ancienne",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 53,
                "module_code" => "LFA12404",
                "name" => "Poésie moderne",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 54,
                "module_code" => "LFA12504",
                "name" => "Phonétique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 55,
                "module_code" => "LFA12604",
                "name" => "Philosophie",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 56,
                "module_code" => "LFA12704",
                "name" => "Langues",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 57,
                "module_code" => "LFA23104",
                "name" => "Grammaire 3",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 58,
                "module_code" => "LFA23204",
                "name" => "Phonologie",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 59,
                "module_code" => "LFA23304",
                "name" => " Récit Ancien",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 60,
                "module_code" => "LFA23404",
                "name" => "Récit moderne",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 61,
                "module_code" => "LFA23504",
                "name" => "Ancien critique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 62,
                "module_code" => "LFA23604",
                "name" => "Lexique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 63,
                "module_code" => "LFA24104",
                "name" => "Morphologie",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 64,
                "module_code" => "LFA24204",
                "name" => "Syntaxe",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 65,
                "module_code" => "LFA24304",
                "name" => "Litterature marocaine et andalouse",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 66,
                "module_code" => "LFA24404",
                "name" => "Théâtre",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 67,
                "module_code" => "LFA24504",
                "name" => "Méthode de la critique littéraire moderne",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 68,
                "module_code" => "LFA24604",
                "name" => "Sémantique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 69,
                "module_code" => "LFA35104",
                "name" => "Théorie de la littérature",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 70,
                "module_code" => "LFA35204",
                "name" => "Analyse du discour",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 71,
                "module_code" => "LFA35304",
                "name" => "Littérature comparée",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 72,
                "module_code" => "LFA35404",
                "name" => "Poésie marocaine moderne",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 73,
                "module_code" => "LFA35504",
                "name" => "Littérature orale",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 74,
                "module_code" => "LFA35604",
                "name" => "Forme de l\'expression numérique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 75,
                "module_code" => "LFA36104",
                "name" => "Ennovation littéraire numérique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 76,
                "module_code" => "LFA36204",
                "name" => "Récit marocain moderne",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 77,
                "module_code" => "LFA36304",
                "name" => "Patrimoine arabe",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 78,
                "module_code" => "LFA36401",
                "name" => "hh",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 79,
                "module_code" => "LFA36404",
                "name" => "Etudes culturelles féminines",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 80,
                "module_code" => "LFA36504",
                "name" => "PFE: Méthodologie de la recherche",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 81,
                "module_code" => "LFA36604",
                "name" => "PFE: Mémoires et séminaires",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 82,
                "module_code" => "LFB35104",
                "name" => "Questions grammaticales",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 83,
                "module_code" => "LFB35204",
                "name" => "Sémiotique du discours et de l\'image",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 84,
                "module_code" => "LFB35304",
                "name" => "Terminologie",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 85,
                "module_code" => "LFB35404",
                "name" => "Modèles syntaxiques",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 86,
                "module_code" => "LFB35504",
                "name" => "Sociolinguistique",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 87,
                "module_code" => "LFB35604",
                "name" => "Linguistique fonctionnelle",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 88,
                "module_code" => "LFB36104",
                "name" => "Modèles sémantiques",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 89,
                "module_code" => "LFB36204",
                "name" => "Syntaxe comparée",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 90,
                "module_code" => "LFB36304",
                "name" => "Morpho-phonologie",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 91,
                "module_code" => "LFB36404",
                "name" => "Modèles pragmatiques",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 92,
                "module_code" => "LFB36504",
                "name" => "PFE: Méthodologie de la recherche",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 93,
                "module_code" => "LFB36604",
                "name" => "PFE: Mémoires et séminaires",
                "class_ids" => "LFARABE",
            ],
            [
                "module_id" => 94,
                "module_code" => "LFE11104",
                "name" => "READING COMPREHENSION  AND PRECIS 1",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 95,
                "module_code" => "LFE11204",
                "name" => "PARAGRAPH WRITING",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 96,
                "module_code" => "LFE11304",
                "name" => "GRAMMAR 1",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 97,
                "module_code" => "LFE11404",
                "name" => "SPOKEN ENGLISH",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 98,
                "module_code" => "LFE11504",
                "name" => "GUIDED READING",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 99,
                "module_code" => "LFE11604",
                "name" => "STUDY SKILLS",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 100,
                "module_code" => "LFE11704",
                "name" => "LANGUES I",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 101,
                "module_code" => "LFE12104",
                "name" => "READING COMPREHENSION AND PRECIS  2",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 102,
                "module_code" => "LFE12204",
                "name" => "COMPOSITION 1",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 103,
                "module_code" => "LFE12304",
                "name" => "GRAMMAR 2",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 104,
                "module_code" => "LFE12404",
                "name" => "ORAL COMMUNICATION",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 105,
                "module_code" => "LFE12504",
                "name" => "READINGS IN CULTURE",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 106,
                "module_code" => "LFE12604",
                "name" => "BUSINESS COMMUNICATION",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 107,
                "module_code" => "LFE12704",
                "name" => "LANGUES II",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 108,
                "module_code" => "LFE23104",
                "name" => "EXTENSIVE READING",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 109,
                "module_code" => "LFE23204",
                "name" => "COMPOSITION 2",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 110,
                "module_code" => "LFE23304",
                "name" => "GRAMMAR 3",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 111,
                "module_code" => "LFE23403",
                "name" => "PUBLIC SPEAKING AND DEBATING",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 112,
                "module_code" => "LFE23504",
                "name" => "BRITISH CULTURE AND SOCIETY/ CULTURE AND SOCIETY IN THE US",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 113,
                "module_code" => "LFE23604",
                "name" => "INITIATION TO TRANSLATION",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 114,
                "module_code" => "LFE24104",
                "name" => "INTRODUCTION TO LITERATUR",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 115,
                "module_code" => "LFE24204",
                "name" => "ADVANCED COMPOSITION  AND INTRODUCTION TO RESEARCH",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 116,
                "module_code" => "LFE24304",
                "name" => "INTRODUCTION  TO LINGUISTICS",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 117,
                "module_code" => "LFE24404",
                "name" => "INTRODUCTION TO MEDIA STUDIES",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 118,
                "module_code" => "LFE24504",
                "name" => "INTRODUCTION TO CULTURAL STUDIES",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 119,
                "module_code" => "LFE24604",
                "name" => "TRANSLATION  (ARABIC-ENGLISH - ARABIC)",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 120,
                "module_code" => "LFE35104",
                "name" => "LITERARY TRADITIONS 1 :REALISM/ ROMANTICISM",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 121,
                "module_code" => "LFE35204",
                "name" => "LITERATURE IN THE ENGLISH SPEAKING WORLD",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 122,
                "module_code" => "LFE35304",
                "name" => "INTERCULTURAL COMMUNICATION",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 123,
                "module_code" => "LFE35404",
                "name" => "CRITICAL APPROACHES",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 124,
                "module_code" => "LFE35504",
                "name" => "CLASSICAL DRAMA",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 125,
                "module_code" => "LFE35604",
                "name" => "19th CENT NOVEL",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 126,
                "module_code" => "LFE36104",
                "name" => "LITERARY TRADITIONS 2 MOD POSMODERNISM",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 127,
                "module_code" => "LFE36204",
                "name" => "PFE",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 128,
                "module_code" => "LFE36304",
                "name" => "PFE",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 129,
                "module_code" => "LFE36404",
                "name" => "GENDER STUDIES AND DEVELOPMENT",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 130,
                "module_code" => "LFE36504",
                "name" => "MODERN DRAMA",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 131,
                "module_code" => "LFE36604",
                "name" => "MODERN NOVEL",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 132,
                "module_code" => "LFN35104",
                "name" => "Schools  of Linguistics",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 133,
                "module_code" => "LFN35204",
                "name" => "Advanced Multilingual Translation",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 134,
                "module_code" => "LFN35304",
                "name" => "Intercultural Communication",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 135,
                "module_code" => "LFN35404",
                "name" => "Applied Linguistics",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 136,
                "module_code" => "LFN35504",
                "name" => "Sociolinguistics",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 137,
                "module_code" => "LFN35604",
                "name" => "Psycholinguistics",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 138,
                "module_code" => "LFN36104",
                "name" => "Syntax",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 139,
                "module_code" => "LFN36204",
                "name" => "PFE",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 140,
                "module_code" => "LFN36304",
                "name" => "PFE",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 141,
                "module_code" => "LFN36404",
                "name" => "Semantics and pragmatics",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 142,
                "module_code" => "LFN36504",
                "name" => "Phonology and morphology",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 143,
                "module_code" => "LFN36604",
                "name" => "Discourse Analysis",
                "class_ids" => "LFENGLI",
            ],
            [
                "module_id" => 144,
                "module_code" => "LFF11104",
                "name" => "Grammaire I",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 145,
                "module_code" => "LFF11204",
                "name" => "Phonétique",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 146,
                "module_code" => "LFF11304",
                "name" => "Typologie des textes narratifs",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 147,
                "module_code" => "LFF11404",
                "name" => "initiation aux genres dramatiques",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 148,
                "module_code" => "LFF11504",
                "name" => "Histoire des idées (Moyen âge-17ème siècle)",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 149,
                "module_code" => "LFF11604",
                "name" => "Les grands mythes",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 150,
                "module_code" => "LFF11704",
                "name" => "Langues I",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 151,
                "module_code" => "LFF12104",
                "name" => "Grammaire II",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 152,
                "module_code" => "LFF12204",
                "name" => "Lexicographie",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 153,
                "module_code" => "LFF12304",
                "name" => "Catégorie du récit",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 154,
                "module_code" => "LFF12404",
                "name" => "Poésie et versification",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 155,
                "module_code" => "LFF12504",
                "name" => "Histoire de la littérature, histoire des idées et des arts",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 156,
                "module_code" => "LFF12604",
                "name" => "Introduction à l\'interculturel",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 157,
                "module_code" => "LFF12704",
                "name" => "Langues II",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 158,
                "module_code" => "LFF23104",
                "name" => "Morphosyntaxe I",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 159,
                "module_code" => "LFF23204",
                "name" => "Lexicologie",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 160,
                "module_code" => "LFF23304",
                "name" => "Analyse du roman (XIXème siècle)",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 161,
                "module_code" => "LFF23404",
                "name" => "Théâtre classique17ème siècle",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 162,
                "module_code" => "LFF23504",
                "name" => "Histoire  des idées et de l\'art 19ème siècle",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 163,
                "module_code" => "LFF23604",
                "name" => "Initiation à la traduction",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 164,
                "module_code" => "LFF24104",
                "name" => "Morphosyntaxe II",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 165,
                "module_code" => "LFF24204",
                "name" => "Initiation à la linguistique",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 166,
                "module_code" => "LFF24304",
                "name" => "Poésie(XIXème siècle)",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 167,
                "module_code" => "LFF24404",
                "name" => "Théâtre romantique",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 168,
                "module_code" => "LFF24504",
                "name" => "Histoire des idées et de l\'art (20ème siècle)",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 169,
                "module_code" => "LFF24604",
                "name" => "initiation à la recherche",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 170,
                "module_code" => "LFF35104",
                "name" => "Roman",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 171,
                "module_code" => "LFF35204",
                "name" => "Formes brèves (Nouvelles, fables, maximes contes)",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 172,
                "module_code" => "LFF35304",
                "name" => "Théâtre",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 173,
                "module_code" => "LFF35404",
                "name" => "Poésie",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 174,
                "module_code" => "LFF35504",
                "name" => "Critique littéraire",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 175,
                "module_code" => "LFF35604",
                "name" => "NTIC et Méthodes de Recherche",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 176,
                "module_code" => "LFF36104",
                "name" => "Littérature maghrébine",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 177,
                "module_code" => "LFF36204",
                "name" => "Littérature subsaharienne",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 178,
                "module_code" => "LFF36304",
                "name" => "Arts et littératures",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 179,
                "module_code" => "LFF36404",
                "name" => "Introduction à la littérature générale et comparée",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 180,
                "module_code" => "LFF36504",
                "name" => "Projet Tutoré ou Stage : Séminaires",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 181,
                "module_code" => "LFF36604",
                "name" => "Projet Tutoré ou Stage : Suivi",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 182,
                "module_code" => "LFR35104",
                "name" => "Courants linguistiques",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 183,
                "module_code" => "LFR35204",
                "name" => "Sociolinguistique",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 184,
                "module_code" => "LFR35304",
                "name" => "Syntaxe",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 185,
                "module_code" => "LFR35404",
                "name" => "Sémantique",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 186,
                "module_code" => "LFR35504",
                "name" => "Analyse du Discours",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 187,
                "module_code" => "LFR35604",
                "name" => "NTIC et Méthodes de Recherche",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 188,
                "module_code" => "LFR36104",
                "name" => "Pragmatique",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 189,
                "module_code" => "LFR36204",
                "name" => "Phonologie",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 190,
                "module_code" => "LFR36304",
                "name" => "Dialectologie",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 191,
                "module_code" => "LFR36404",
                "name" => "Sémiotique ou Stylistique ou Rhétorique",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 192,
                "module_code" => "LFR36504",
                "name" => "Projet Tutoré ou Stage : Séminaires",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 193,
                "module_code" => "LFR36604",
                "name" => "Projet Tutoré ou stage :Suivi",
                "class_ids" => "LFFRANC",
            ],
            [
                "module_id" => 194,
                "module_code" => "LPM11109",
                "name" => "Histoire des arts et des civilisations",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 195,
                "module_code" => "LPM11209",
                "name" => "Introduction à l\'esthétique et au goût artistique",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 196,
                "module_code" => "LPM11309",
                "name" => "Histoire du graphisme et des médias numériques",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 197,
                "module_code" => "LPM11409",
                "name" => "Principes de créativité et d\'innovation",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 198,
                "module_code" => "LPM11509",
                "name" => "Initiation à l\'informatique et maitrise des logiciels1",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 199,
                "module_code" => "LPM11609",
                "name" => "Pratiques artistiques et techniques  1",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 200,
                "module_code" => "LPM11709",
                "name" =>
                "Compétences de communication  et  d\'apprentissage en anglais",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 201,
                "module_code" => "LPM12109",
                "name" => "Introduction à l\'étude de la publicité",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 202,
                "module_code" => "LPM12209",
                "name" => "Introduction à l\'impression, l\'édition et l\'emballage",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 203,
                "module_code" => "LPM12309",
                "name" => "Principes de marketing",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 204,
                "module_code" => "LPM12409",
                "name" => "Art et littérature comparée",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 205,
                "module_code" => "LPM12509",
                "name" => "Initiation a l\'informatique et maitrise des logiciels",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 206,
                "module_code" => "LPM12609",
                "name" => "Pratiques artistiques et techniques  2",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 207,
                "module_code" => "LPM12709",
                "name" =>
                "Compétences de communication et d\'apprentissage en  français",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 208,
                "module_code" => "LPM23109",
                "name" => "Terme artistique",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 209,
                "module_code" => "LPM23209",
                "name" => "Analyse d\'image",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 210,
                "module_code" => "LPM23309",
                "name" => "Techniques  de l\'audio-visuel",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 211,
                "module_code" => "LPM23409",
                "name" => " Les bases de la vidéo et du film",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 212,
                "module_code" => "LPM23509",
                "name" => "pratiques artistiques et techniques 3",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 213,
                "module_code" => "LPM23609",
                "name" =>
                "Compétences de communication  et  d\'apprentissage en  arabe",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 214,
                "module_code" => "LPM24109",
                "name" => "Ingénierie du son",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 215,
                "module_code" => "LPM24209",
                "name" => "Infographie",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 216,
                "module_code" => "LPM24309",
                "name" => "Typographie",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 217,
                "module_code" => "LPM24409",
                "name" => "Photographie et eclairage",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 218,
                "module_code" => "LPM24509",
                "name" => "Pratiques artistiques et techniques 4",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 219,
                "module_code" => "LPM24609",
                "name" => "Langues et informatique",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 220,
                "module_code" => "LPM35109",
                "name" =>
                "Principes et bases de la conception bidimensionnelle et trid",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 221,
                "module_code" => "LPM35209",
                "name" => "Conception d\'affiches publicitaires",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 222,
                "module_code" => "LPM35309",
                "name" =>
                "Théories des couleurs et applications en design et en public",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 223,
                "module_code" => "LPM35409",
                "name" => "Publicité et comportement du consommateur",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 224,
                "module_code" => "LPM35509",
                "name" => "Analyse et critique du discours publicitaire",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 225,
                "module_code" => "LPM35609",
                "name" => "la preparation de la recherche accademique",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 226,
                "module_code" => "LPM36109",
                "name" => " Travaux d\'ateliers",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 227,
                "module_code" => "LPM36209",
                "name" => "Communication et animation culturelle",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 228,
                "module_code" => "LPM36309",
                "name" => "La culture juridique et les droits de l\'homme",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 229,
                "module_code" => "LPM36409",
                "name" => "Recherches et apprentissages en milieu  professionnel",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 230,
                "module_code" => "LPM36509",
                "name" => "Recherches et apprentissages en milieu  professionnel",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 231,
                "module_code" => "LPM36609",
                "name" => "Recherches et apprentissages en milieu  professionnel",
                "class_ids" => "LPMARTM",
            ],
            [
                "module_id" => 232,
                "module_code" => "LPS11109",
                "name" => "Histoire des arts et des civilisations",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 233,
                "module_code" => "LPS11209",
                "name" => "Esthétique et théories de l\'art",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 234,
                "module_code" => "LPS11309",
                "name" => "Introduction à l\'étude du théâtre occidental",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 235,
                "module_code" => "LPS11409",
                "name" => "Principes de créativité et d\'innovation",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 236,
                "module_code" => "LPS11509",
                "name" => "Initiation a l\'informatique et maitrise des logiciels 1",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 237,
                "module_code" => "LPS11609",
                "name" => "Pratiques artistiques et techniques 1",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 238,
                "module_code" => "LPS11709",
                "name" => "Langues et Communication 1: Langue anglaise",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 239,
                "module_code" => "LPS12109",
                "name" => "Education artistique",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 240,
                "module_code" => "LPS12209",
                "name" => "Introduction à l\'étude du théâtre dans L\'orient arabe",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 241,
                "module_code" => "LPS12309",
                "name" => "Théâtre du Maghreb",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 242,
                "module_code" => "LPS12409",
                "name" => "Ecriture littérale théâtral",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 243,
                "module_code" => "LPS12509",
                "name" => " Initiation a l\'informatique et maitrise des logiciels 2",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 244,
                "module_code" => "LPS12609",
                "name" => "Pratiques artistiques et techniques 2",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 245,
                "module_code" => "LPS12709",
                "name" => "Langues et  Communication 2: langue Française",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 246,
                "module_code" => "LPS23109",
                "name" => "Mise en scène de théâtre",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 247,
                "module_code" => "LPS23209",
                "name" => "Scénographie",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 248,
                "module_code" => "LPS23309",
                "name" => "Dramaturgie",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 249,
                "module_code" => "LPS23409",
                "name" => "Techniques d\'éclairage de théâtre et ingénierie du son",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 250,
                "module_code" => "LPS23509",
                "name" => "pratiques artistiques et techniques 3",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 251,
                "module_code" => "LPS23609",
                "name" => "Langues et communication",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 252,
                "module_code" => "LPS24109",
                "name" => "Mise en scène de théâtre",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 253,
                "module_code" => "LPS24209",
                "name" => "Le théâtre et les méthodes de la critique littéraire",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 254,
                "module_code" => "LPS24309",
                "name" => "Sociologie du théâtre",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 255,
                "module_code" => "LPS24409",
                "name" => "L\'analyse du discours théâtral",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 256,
                "module_code" => "LPS24509",
                "name" => "Pratiques artistique",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 257,
                "module_code" => "LPS24609",
                "name" => "Langues et informatique",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 258,
                "module_code" => "LPS35109",
                "name" => "Adaptation et écriture de scénario",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 259,
                "module_code" => "LPS35209",
                "name" => "Théâtre et technologies numériques",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 260,
                "module_code" => "LPS35309",
                "name" => "Communication et animation culturelle",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 261,
                "module_code" => "LPS35409",
                "name" => "Théâtre et thérapie",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 262,
                "module_code" => "LPS35509",
                "name" => "pratiques artistiques et techniques 5",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 263,
                "module_code" => "LPS35609",
                "name" => "La préparation de la recherche accademique",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 264,
                "module_code" => "LPS36109",
                "name" => "Gestion des Acteurs",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 265,
                "module_code" => "LPS36209",
                "name" => "Gestion des Institutions Culturelles",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 266,
                "module_code" => "LPS36309",
                "name" => "Culture Juridique et Droits Humains",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 267,
                "module_code" => "LPS36409",
                "name" => "Recherches et apprentissages en milieu  professionnel",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 268,
                "module_code" => "LPS36509",
                "name" => "Recherches et apprentissages en milieu  professionnel",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 269,
                "module_code" => "LPS36609",
                "name" => "Recherches et apprentissages en milieu  professionnel",
                "class_ids" => "LPMARTS",
            ],
            [
                "module_id" => 270,
                "module_code" => "PLAV1110",
                "name" => "MOD01",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 271,
                "module_code" => "PLAV1120",
                "name" => "MOD02",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 272,
                "module_code" => "PLAV1130",
                "name" => "MOD03",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 273,
                "module_code" => "PLAV1140",
                "name" => "MOD04",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 274,
                "module_code" => "PLAV1150",
                "name" => "MOD05",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 275,
                "module_code" => "PLAV1160",
                "name" => "MOD06",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 276,
                "module_code" => "PLAV1170",
                "name" => "MOD06",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 277,
                "module_code" => "PLAV1210",
                "name" => "MOD01",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 278,
                "module_code" => "PLAV1220",
                "name" => "MOD02",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 279,
                "module_code" => "PLAV1230",
                "name" => "MOD03",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 280,
                "module_code" => "PLAV1240",
                "name" => "MOD04",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 281,
                "module_code" => "PLAV1250",
                "name" => "MOD05",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 282,
                "module_code" => "PLAV1260",
                "name" => "MOD06",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 283,
                "module_code" => "PLAV1270",
                "name" => "MOD07",
                "class_ids" => "PLMARAV",
            ],
            [
                "module_id" => 284,
                "module_code" => "PLAC1110",
                "name" => "MOD01",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 285,
                "module_code" => "PLAC1120",
                "name" => "MOD02",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 286,
                "module_code" => "PLAC1130",
                "name" => "MOD03",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 287,
                "module_code" => "PLAC1140",
                "name" => "MOD04",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 288,
                "module_code" => "PLAC1150",
                "name" => "MOD05",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 289,
                "module_code" => "PLAC1160",
                "name" => "MOD06",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 290,
                "module_code" => "PLAC1170",
                "name" => "MOD07",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 291,
                "module_code" => "PLAC1210",
                "name" => "MOD01",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 292,
                "module_code" => "PLAC1220",
                "name" => "MOD02",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 293,
                "module_code" => "PLAC1230",
                "name" => "MOD03",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 294,
                "module_code" => "PLAC1240",
                "name" => "MOD04",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 295,
                "module_code" => "PLAC1250",
                "name" => "MOD05",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 296,
                "module_code" => "PLAC1260",
                "name" => "MOD06",
                "class_ids" => "PLMTHAC",
            ],
            [
                "module_id" => 297,
                "module_code" => "PLAC1270",
                "name" => "MOD07",
                "class_ids" => "PLMTHAC",
            ],
        ];

        foreach ($modules as $row) {

            $class_codes = explode(",", $row['class_ids']);
            $class_ids = [];

            foreach ($class_codes as $code) {
                // Assuming $classes is the array mapping class codes to class ids
                // Add a check to ensure the code exists in $classes to avoid errors
                if (isset($classes[$code])) {
                    $class_ids[] = $classes[$code];
                }
            }

            // Implode the array to create a comma-separated string
            $implodedClassIds = implode(",", $class_ids);


            Module::factory()->create([
                'module_id' => $row['module_id'],
                'module_code' => $row['module_code'],
                'name' => $row['name'],
                'class_ids' => $implodedClassIds,
            ]);
        }
    }
}
